apiVersion: v1
kind: Service
metadata:
  name: fantasyroller-service
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Set a specific node port if desired
  type: NodePort
